name: ExplosiveArrows
description: Bows? More like explosive fun!
version: 0.1.0-B1
author: VMPE Development Team
main: jacknoordhuis\explosivearrows\ExplosiveArrows
api:
  - 3.0.0-ALPHA8
  - 3.0.0-ALPHA9
  - 3.0.0-ALPHA10

commands:
  givebow:
    usage: "/givebow <player> <explosion size> <terrain damage> <name>"
    description: "Give a player a custom explosive bow"
    permission: explosivearrows.command.givebow

permissions:
  explosivearrows:
    description: "Access to all ExplosiveBow permissions"
    default: op
    children:
      explosivearrows.command:
        description: "Access to all ExplosiveBow commands"
        default: op
        children:
          explosivearrows.command.givebow:
            description: "Access to the /givebow command"
            default: op
